
package cz.zcu.kiv.eegdatabase.webservices.datadownload;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2015-05-14T13:25:18.909+02:00
 * Generated source version: 2.5.2
 * 
 */
public final class UserDataService_UserDataImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://datadownload.webservices.eegdatabase.kiv.zcu.cz/", "UserDataImplService");

    private UserDataService_UserDataImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserDataImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserDataImplService ss = new UserDataImplService(wsdlURL, SERVICE_NAME);
        UserDataService port = ss.getUserDataImplPort();  
        
        {
        System.out.println("Invoking getExperimentsMetadata...");
        int _getExperimentsMetadata_arg0 = -1963882884;
        cz.zcu.kiv.eegdatabase.webservices.datadownload.ExperimentMetadata _getExperimentsMetadata__return = port.getExperimentsMetadata(_getExperimentsMetadata_arg0);
        System.out.println("getExperimentsMetadata.result=" + _getExperimentsMetadata__return);


        }
        {
        System.out.println("Invoking getDataFiles...");
        try {
            java.util.List<cz.zcu.kiv.eegdatabase.webservices.datadownload.DataFileInfo> _getDataFiles__return = port.getDataFiles();
            System.out.println("getDataFiles.result=" + _getDataFiles__return);

        } catch (UserDataServiceException_Exception e) { 
            System.out.println("Expected exception: UserDataServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking downloadDataFile...");
        int _downloadDataFile_arg0 = 22607057;
        try {
            javax.activation.DataHandler _downloadDataFile__return = port.downloadDataFile(_downloadDataFile_arg0);
            System.out.println("downloadDataFile.result=" + _downloadDataFile__return);

        } catch (UserDataServiceException_Exception e) { 
            System.out.println("Expected exception: UserDataServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addOrUpdateDataFile...");
        cz.zcu.kiv.eegdatabase.webservices.datadownload.DataFileInfo _addOrUpdateDataFile_arg0 = new cz.zcu.kiv.eegdatabase.webservices.datadownload.DataFileInfo();
        _addOrUpdateDataFile_arg0.setAdded(true);
        _addOrUpdateDataFile_arg0.setChanged(true);
        _addOrUpdateDataFile_arg0.setDescription("Description1627996170");
        _addOrUpdateDataFile_arg0.setExperimentId(826267707);
        _addOrUpdateDataFile_arg0.setFileId(345549785);
        _addOrUpdateDataFile_arg0.setFileLength(2756956372741883780l);
        _addOrUpdateDataFile_arg0.setFileName("FileName292517469");
        _addOrUpdateDataFile_arg0.setMimeType("MimeType-1192321183");
        javax.activation.DataHandler _addOrUpdateDataFile_arg1 = null;
        try {
            int _addOrUpdateDataFile__return = port.addOrUpdateDataFile(_addOrUpdateDataFile_arg0, _addOrUpdateDataFile_arg1);
            System.out.println("addOrUpdateDataFile.result=" + _addOrUpdateDataFile__return);

        } catch (UserDataServiceException_Exception e) { 
            System.out.println("Expected exception: UserDataServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getHardware...");
        java.util.List<cz.zcu.kiv.eegdatabase.webservices.datadownload.HardwareInfo> _getHardware__return = port.getHardware();
        System.out.println("getHardware.result=" + _getHardware__return);


        }
        {
        System.out.println("Invoking addOrUpdateHardware...");
        cz.zcu.kiv.eegdatabase.webservices.datadownload.HardwareInfo _addOrUpdateHardware_arg0 = new cz.zcu.kiv.eegdatabase.webservices.datadownload.HardwareInfo();
        _addOrUpdateHardware_arg0.setAdded(true);
        _addOrUpdateHardware_arg0.setChanged(true);
        _addOrUpdateHardware_arg0.setDescription("Description958182211");
        java.util.List<java.lang.Integer> _addOrUpdateHardware_arg0ExperimentIds = new java.util.ArrayList<java.lang.Integer>();
        java.lang.Integer _addOrUpdateHardware_arg0ExperimentIdsVal1 = Integer.valueOf(1447831932);
        _addOrUpdateHardware_arg0ExperimentIds.add(_addOrUpdateHardware_arg0ExperimentIdsVal1);
        _addOrUpdateHardware_arg0.getExperimentIds().addAll(_addOrUpdateHardware_arg0ExperimentIds);
        _addOrUpdateHardware_arg0.setHardwareId(802572526);
        _addOrUpdateHardware_arg0.setTitle("Title1681568579");
        _addOrUpdateHardware_arg0.setType("Type840563584");
        int _addOrUpdateHardware__return = port.addOrUpdateHardware(_addOrUpdateHardware_arg0);
        System.out.println("addOrUpdateHardware.result=" + _addOrUpdateHardware__return);


        }
        {
        System.out.println("Invoking addOfUpdateWeather...");
        cz.zcu.kiv.eegdatabase.webservices.datadownload.WeatherInfo _addOfUpdateWeather_arg0 = new cz.zcu.kiv.eegdatabase.webservices.datadownload.WeatherInfo();
        _addOfUpdateWeather_arg0.setAdded(true);
        _addOfUpdateWeather_arg0.setChanged(false);
        _addOfUpdateWeather_arg0.setDescription("Description-1869635500");
        _addOfUpdateWeather_arg0.setTitle("Title777583971");
        _addOfUpdateWeather_arg0.setWeatherId(2104426702);
        int _addOfUpdateWeather__return = port.addOfUpdateWeather(_addOfUpdateWeather_arg0);
        System.out.println("addOfUpdateWeather.result=" + _addOfUpdateWeather__return);


        }
        {
        System.out.println("Invoking addOrUpdateExperiment...");
        cz.zcu.kiv.eegdatabase.webservices.datadownload.ExperimentInfo _addOrUpdateExperiment_arg0 = new cz.zcu.kiv.eegdatabase.webservices.datadownload.ExperimentInfo();
        _addOrUpdateExperiment_arg0.setAdded(false);
        _addOrUpdateExperiment_arg0.setChanged(false);
        cz.zcu.kiv.eegdatabase.webservices.datadownload.DigitizationInfo _addOrUpdateExperiment_arg0DigitizationInfo = new cz.zcu.kiv.eegdatabase.webservices.datadownload.DigitizationInfo();
        _addOrUpdateExperiment_arg0DigitizationInfo.setFilter("Filter976372071");
        _addOrUpdateExperiment_arg0DigitizationInfo.setGain(0.6307294f);
        _addOrUpdateExperiment_arg0DigitizationInfo.setSamplingRate(0.64843404f);
        _addOrUpdateExperiment_arg0.setDigitizationInfo(_addOrUpdateExperiment_arg0DigitizationInfo);
        _addOrUpdateExperiment_arg0.setEndTimeInMillis(8497866308395292143l);
        _addOrUpdateExperiment_arg0.setExperimentId(-139698831);
        java.util.List<java.lang.Integer> _addOrUpdateExperiment_arg0HwIds = new java.util.ArrayList<java.lang.Integer>();
        java.lang.Integer _addOrUpdateExperiment_arg0HwIdsVal1 = Integer.valueOf(-11062181);
        _addOrUpdateExperiment_arg0HwIds.add(_addOrUpdateExperiment_arg0HwIdsVal1);
        _addOrUpdateExperiment_arg0.getHwIds().addAll(_addOrUpdateExperiment_arg0HwIds);
        _addOrUpdateExperiment_arg0.setOwnerId(281820434);
        _addOrUpdateExperiment_arg0.setPrivateFlag(656114226);
        _addOrUpdateExperiment_arg0.setResearchGroupId(-873583062);
        _addOrUpdateExperiment_arg0.setScenarioId(-480221897);
        _addOrUpdateExperiment_arg0.setStartTimeInMillis(407249907816215667l);
        _addOrUpdateExperiment_arg0.setSubjectGroupId(947728683);
        _addOrUpdateExperiment_arg0.setSubjectPersonId(-676613386);
        _addOrUpdateExperiment_arg0.setTemperature(951631205);
        _addOrUpdateExperiment_arg0.setTitle("Title-305029258");
        _addOrUpdateExperiment_arg0.setWeatherId(116959096);
        _addOrUpdateExperiment_arg0.setWeatherNote("WeatherNote-1656158237");
        int _addOrUpdateExperiment__return = port.addOrUpdateExperiment(_addOrUpdateExperiment_arg0);
        System.out.println("addOrUpdateExperiment.result=" + _addOrUpdateExperiment__return);


        }
        {
        System.out.println("Invoking addOrUpdatePerson...");
        cz.zcu.kiv.eegdatabase.webservices.datadownload.PersonInfo _addOrUpdatePerson_arg0 = new cz.zcu.kiv.eegdatabase.webservices.datadownload.PersonInfo();
        _addOrUpdatePerson_arg0.setAdded(true);
        _addOrUpdatePerson_arg0.setChanged(false);
        _addOrUpdatePerson_arg0.setDefaultGroupId(1076188263);
        _addOrUpdatePerson_arg0.setEducationalLevel("EducationalLevel1118417100");
        _addOrUpdatePerson_arg0.setGender(614024690);
        _addOrUpdatePerson_arg0.setGivenName("GivenName2109938874");
        _addOrUpdatePerson_arg0.setPersonId(1803888770);
        _addOrUpdatePerson_arg0.setSurname("Surname-1125320679");
        int _addOrUpdatePerson__return = port.addOrUpdatePerson(_addOrUpdatePerson_arg0);
        System.out.println("addOrUpdatePerson.result=" + _addOrUpdatePerson__return);


        }
        {
        System.out.println("Invoking getResearchGroups...");
        java.util.List<cz.zcu.kiv.eegdatabase.webservices.datadownload.ResearchGroupInfo> _getResearchGroups__return = port.getResearchGroups();
        System.out.println("getResearchGroups.result=" + _getResearchGroups__return);


        }
        {
        System.out.println("Invoking getExperiments...");
        java.util.List<cz.zcu.kiv.eegdatabase.webservices.datadownload.ExperimentInfo> _getExperiments__return = port.getExperiments();
        System.out.println("getExperiments.result=" + _getExperiments__return);


        }
        {
        System.out.println("Invoking getWeather...");
        java.util.List<cz.zcu.kiv.eegdatabase.webservices.datadownload.WeatherInfo> _getWeather__return = port.getWeather();
        System.out.println("getWeather.result=" + _getWeather__return);


        }
        {
        System.out.println("Invoking getScenarios...");
        java.util.List<cz.zcu.kiv.eegdatabase.webservices.datadownload.ScenarioInfo> _getScenarios__return = port.getScenarios();
        System.out.println("getScenarios.result=" + _getScenarios__return);


        }
        {
        System.out.println("Invoking isServiceAvailable...");
        boolean _isServiceAvailable__return = port.isServiceAvailable();
        System.out.println("isServiceAvailable.result=" + _isServiceAvailable__return);


        }
        {
        System.out.println("Invoking getPeople...");
        java.util.List<cz.zcu.kiv.eegdatabase.webservices.datadownload.PersonInfo> _getPeople__return = port.getPeople();
        System.out.println("getPeople.result=" + _getPeople__return);


        }
        {
        System.out.println("Invoking addOrUpdateResearchGroup...");
        cz.zcu.kiv.eegdatabase.webservices.datadownload.ResearchGroupInfo _addOrUpdateResearchGroup_arg0 = new cz.zcu.kiv.eegdatabase.webservices.datadownload.ResearchGroupInfo();
        _addOrUpdateResearchGroup_arg0.setAdded(true);
        _addOrUpdateResearchGroup_arg0.setChanged(true);
        _addOrUpdateResearchGroup_arg0.setDescription("Description1812215473");
        _addOrUpdateResearchGroup_arg0.setOwnerId(1995628064);
        _addOrUpdateResearchGroup_arg0.setResearchGroupId(-1631967931);
        _addOrUpdateResearchGroup_arg0.setTitle("Title905964029");
        int _addOrUpdateResearchGroup__return = port.addOrUpdateResearchGroup(_addOrUpdateResearchGroup_arg0);
        System.out.println("addOrUpdateResearchGroup.result=" + _addOrUpdateResearchGroup__return);


        }
        {
        System.out.println("Invoking addOrUpdateScenario...");
        cz.zcu.kiv.eegdatabase.webservices.datadownload.ScenarioInfo _addOrUpdateScenario_arg0 = new cz.zcu.kiv.eegdatabase.webservices.datadownload.ScenarioInfo();
        _addOrUpdateScenario_arg0.setAdded(false);
        _addOrUpdateScenario_arg0.setChanged(false);
        _addOrUpdateScenario_arg0.setDescription("Description1228013167");
        _addOrUpdateScenario_arg0.setMimeType("MimeType188006086");
        _addOrUpdateScenario_arg0.setOwnerId(1897602878);
        _addOrUpdateScenario_arg0.setResearchGroupId(1711215628);
        _addOrUpdateScenario_arg0.setScenarioId(-491420628);
        _addOrUpdateScenario_arg0.setScenarioLength(-729350610);
        _addOrUpdateScenario_arg0.setScenarioName("ScenarioName-901773074");
        _addOrUpdateScenario_arg0.setTitle("Title-1882499408");
        int _addOrUpdateScenario__return = port.addOrUpdateScenario(_addOrUpdateScenario_arg0);
        System.out.println("addOrUpdateScenario.result=" + _addOrUpdateScenario__return);


        }

        System.exit(0);
    }

}
