
package cz.zcu.kiv.eegdatabase.webservices.datadownload;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2015-05-14T13:25:18.989+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "UserDataServiceException", targetNamespace = "http://datadownload.webservices.eegdatabase.kiv.zcu.cz/")
public class UserDataServiceException_Exception extends Exception {
    
    private cz.zcu.kiv.eegdatabase.webservices.datadownload.UserDataServiceException userDataServiceException;

    public UserDataServiceException_Exception() {
        super();
    }
    
    public UserDataServiceException_Exception(String message) {
        super(message);
    }
    
    public UserDataServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UserDataServiceException_Exception(String message, cz.zcu.kiv.eegdatabase.webservices.datadownload.UserDataServiceException userDataServiceException) {
        super(message);
        this.userDataServiceException = userDataServiceException;
    }

    public UserDataServiceException_Exception(String message, cz.zcu.kiv.eegdatabase.webservices.datadownload.UserDataServiceException userDataServiceException, Throwable cause) {
        super(message, cause);
        this.userDataServiceException = userDataServiceException;
    }

    public cz.zcu.kiv.eegdatabase.webservices.datadownload.UserDataServiceException getFaultInfo() {
        return this.userDataServiceException;
    }
}
